### ISSUE TITLE
Suggestion to rename repository

### ISSUE THREAD

**Issue by vitormattos** [theCalcaholic/nextcloud-secrets#14]
All Nextcloud apps need to have the root folder of the app equal to the appId. When we clone the directory of this app inside apps folder, will be necessary change the folder name to secrets or clone directly to folder secrets. As a new developer, do this is a bit complex because is necessary read a documentation explaining this, but developers only clone and want start to work.

Other point is about continuous integrations with GitHub Actions. At [this PR](https://github.com/theCalcaholic/nextcloud-secrets/pull/11/files) I needed to change all the [default templates created by Nextcloud](https://github.com/nextcloud/.github)   to work fine with the repository name different of appId.

I suggest to rename the repository from nextcloud-secrets to only secrets, as the same of appId.

**Comment by theCalcaholic** [comment]
I feel ambivalent about this... While it would make building the repository easier, it would also make the repository name very generic.

I would have no idea what a project named "secrets" is supposed to be and I would probably assume a collection of credentials or a standalone tool.

I'll think about it!

**Comment by vitormattos** [comment]
Maybe a good way to solve this problem will be to put the information about the repository name on README to help new developers.

**Comment by theCalcaholic** [comment]
I think I'm okay with the current naming. But I should definitely add more info to the Readme :)
