### ISSUE TITLE
Remove Oracle tests from GitHub Actions

### ISSUE THREAD

**Issue by vitormattos** [theCalcaholic/nextcloud-secrets#17]
Only a suggestion to appreciate your opinion @theCalcaholic because it take a lot of time to finish the CI.

**Comment by theCalcaholic** [comment]
I agree. I don't think the Oracle DB is very relevant. :+1:

**Comment by theCalcaholic** [comment]
I removed the oracle test in dafb403b1267f8ff230a742866789941147a618c
