### ISSUE TITLE
Cannot update to Secrets 1.3.1

### ISSUE THREAD

**Issue by farsider-uk** [theCalcaholic/nextcloud-secrets#23]
Currently installed:

Debian: Bullseye
Nextcloud: 25.0.3 stable branch
Secrets: 1.0.1

When I go to update Secrets to v1.3.1 using the Web GUI, Nextcloud is put into maintenance mode and never comes out. When maintenance mode is manually disabled, I am prompted for a NextCloud upgrade. When performing the upgrade, the upgrade hangs at the 'updating database' section and never completes.

**Comment by theCalcaholic** [comment]
Hi, thanks for the report. Can you post the logs from the upgrade please?.
Also, please let me know what database you are using.

**Comment by farsider-uk** [comment]
Oddly, nothing appears in my nextcloud.log when I kick off the upgrade. Is there any other logs I should be checking?

Here's the most recent line from nextcloud.log

`{"reqId":"8kKbEgAX9GgqaDupcNPV","level":3,"time":"2023-01-30T00:10:02+00:00","remoteAddr":"","user":"--","app":"PHP","method":"","url":"--","message":"Cannot declare class OCA\\Secrets\\Cron\\CleanupExpiredSecrets, because the name is already in use at /var/www/nextcloud/apps/secrets/lib/Cron/SecretCleanup.php#14","userAgent":"--","version":"25.0.3.2","data":{"app":"PHP"}}`

DB is MariaDB.

**Comment by theCalcaholic** [comment]
That's really weird... If there's no exception (which would be logged), I don't understand why the process doesn't complete.

You could try to remove all existing secrets, if that's okay for your use case (`mysql -u <dbuser> -p -D <dbname> -e "DELETE FROM oc_secrets;"`) and then try the upgrade again.

**Comment by farsider-uk** [comment]
> That's really weird... If there's no exception (which would be logged), I don't understand why the process doesn't complete.
> 
> You could try to remove all existing secrets, if that's okay for your use case (`mysql -u <dbuser> -p -D <dbname> -e "DELETE FROM oc_secrets;"`) and then try the upgrade again.

Thanks for the update but unfortunately that didn't improve the situation. 

As mentioned by @erryKinq, I can remove Secrets and reinstall but cannot Enable. It just hangs when I click Enable....and nothing appears in my nextcloud.log.

**Comment by theCalcaholic** [comment]
@erryKinq were you able to enable the app or do you find yourself in the same situation as @farsider-uk ?

**Comment by theCalcaholic** [comment]
@farsider-uk Did you ever try to run `occ app:update -- secrets` (you may have to run the command like this: `sudo -u www-data php /path/to/your/nextcloud/occ app:update -- secrets`)? If not, please do that before proceeding.

Otherwise, there's one more option. To completely remove Secrets from your nextcloud instance, first, make sure the app is disabled, then execute the following SQL statements:

```sql
DELETE FROM oc_migrations WHERE app='secrets';
DROP TABLE oc_secrets;
```
or as mysql commands:
```sh
mysql -u <dbuser> -p -D <dbname> -e "DELETE FROM oc_migrations WHERE app='secrets';"
mysql -u <dbuser> -p -D <dbname> -e "DROP TABLE oc_secrets;"
```

After that enable Secrets again.
Please let me know if any of this fixes your issues.

**Comment by erryKinq** [comment]
I simply uninstalled the app and wanted to install it again, but since the Nextcloud store still said something about "download and update", i let it go. After a few days, it only said download and install and that's what i did. now the app works again as usual.

**Comment by farsider-uk** [comment]
Thanks for the steps @theCalcaholic. This has resolved the issue. To confirm, this is the steps I followed:

1. Disable Secrets v1.0.1
2. Uninstall Secrets v1.0.1
3. Execute `DELETE FROM oc_migrations WHERE app='secrets';` & `DROP TABLE oc_secrets;` from the Nextcloud Database
4. Restart my Nextcloud instance
5. I was then able to Download Secrets v1.3.1 as if it was a new install from the NC WebGUI. This completed successfully and all is working as expected.

Thanks for your support.

**Comment by theCalcaholic** [comment]
@farsider-uk I'm glad to hear that. Hopefully issues like these won't occur in the future after the changes made in 1.3.1

**Comment by farsider-uk** [comment]
FWIW, just updated to v3.4 without any problems. 

Thank you for Secrets. I use it a lot and it’s a great tool.
