### ISSUE TITLE
Does not work with the Nextcloud 25.0.4 update

### ISSUE THREAD

**Issue by aagarop** [theCalcaholic/nextcloud-secrets#26]
I was unable to update Nextcloud before disabling the Secrets app. 
After upgrade to 25.0.4 the application does not want to be activated anymore (OCC / Web).

**Comment by theCalcaholic** [comment]
Hi, thanks for the report. I did not have any trouble with secrets on Nextcloud 25.0.4 and will require more information to reproduce and help with your issue.

Do you get any error message when attempting to enable secrets or do your logs show anything that might be related?
Also, please let me know which version of secrets that you are running.

**Comment by aagarop** [comment]
Hi, thanks for the reply
I try to install version 1.4.0 from the webui. When I install it the loading spinner runs without limit, when I refresh, the application is installed but not activated. When I try to activate it, it does the same thing. 
Interesting information, from the webui it shows me version 1.4.0 but from occ it's version 1.0.1 that is installed.
I will try to install it from the source
