### ISSUE TITLE
Don't directly show the secret

### ISSUE THREAD

**Issue by papst01** [theCalcaholic/nextcloud-secrets#32]
If reaching the secret page, don't show the secret directly. It is better to make button to open the secret and warn before pushing the button, that this is one-time-button-push.

The usual scenario to address this enhancement is the following: IT-guy and IT-guy are sharing secrets via mail. Within the mail a manager is part of the mail recipient list, who want's to be informed that the guys work. And sometimes they (the managers) click randomly on links and so they are destroying the secret.

**Comment by theCalcaholic** [comment]
Thanks for the suggestion, I like it. I'm thinking of other use cases that would benefit from it - for example if you first open the secret on your phone, but want to store it on your computer it would be nice to have require recipient confirmation before requesting the encrypted data.

I'll keep it in the backlog!

**Comment by theCalcaholic** [comment]
This feature is now in main and will be released with the next version
