### ISSUE TITLE
Secret content field problem

### ISSUE THREAD

**Issue by Jerome-Herbinet** [theCalcaholic/nextcloud-secrets#35]
Hi,

After creating and saving a secret, I have two problems: 
- When I navigate between secrets (if several have been created), the field containing the content of the secret (textarea) remains the same. 
- If I refresh the entire page by clicking on the "Secrets" app icon, I can no longer see the contents of the secrets I own... and I get a message telling me that it is impossible to decrypt the secret, because the key is not available locally. 

I'm having trouble understanding whether these are bugs or whether I haven't understood how this application is supposed to work. Can you help? 

I'm using Nexctloud 26.0.2 with the latest version of "Secrets".

Please watch below my test : 

[Capture vidéo du 02-06-2023 10:23:47.webm](https://github.com/theCalcaholic/nextcloud-secrets/assets/33763786/75ec8a52-832b-4fda-ab47-e9e84cbc1d38)

Thanks for reading me.
Jérôme

**Comment by theCalcaholic** [comment]
Thanks for reporting. To answer your question: The first behavior you are describing is a bug, the second one is expected. As the secrets are stored end-to-end decrypted, they can't be displayed locally, because the key is lost as soon as you leave the page (and have not copied the share link).

However, I'll look into the first issue you are describing

**Comment by theCalcaholic** [comment]
Update: I found the issue. The fix is on the main branch and will be included in the next release.

Btw, you can still safely share your secrets - the values are correct, they are just not displayed correctly in the app

**Comment by Jerome-Herbinet** [comment]
Thanks for your answer and your fix 🙂
Concerning the message which tells that it is impossible to decrypt the secret, because the key is not available locally ... I suggest to change its design, like the green end-to-end encryption message, maybe in red instead, but more discrete anyway because IMO when it's so enormous, user may think there is a bug. What do you think ? After that, I can try to make a PR.
