### ISSUE TITLE
Text area overflows when resizing.

### ISSUE THREAD

**Issue by aris-l** [theCalcaholic/nextcloud-secrets#36]
How about adding "resize: none" at /src/Secret.vue:176 for better responsive experience?
![1](https://github.com/theCalcaholic/nextcloud-secrets/assets/60441047/2f0131e8-cd42-4148-a585-d94b4ffec49a)

**Comment by theCalcaholic** [comment]
Good call! I'll change that

**Comment by theCalcaholic** [comment]
Fix is on main and will be included in the next release
