### ISSUE TITLE
Cannot open the link: the page doesn't exist

### ISSUE THREAD

**Issue by ostasevych** [theCalcaholic/nextcloud-secrets#37]
The app is not working. When trying to open the shared link I am getting the error that this page doesn't exist.
The log shows:
```
[PHP] Error: Undefined array key "activeSectionId" at /var/www/html/nextcloud/apps/settings/templates/settings/frame.php#85
```

NC: 26.0.2, bare metal with Ubuntu 22.04 onboard.

**Comment by theCalcaholic** [comment]
Do you get this error consistently? The error from your logs looks unrelated to the secrets app.


Unfortunately I can't do much about it, unless I can reproduce the issue or get more insightful logs. Maybe there's something logged in the browser though. Can you please try the following:

1. Open a shared secret in your browser
2. Once you encounter the issue, press Ctrl+Shift+K (should open the javascript debugging console
3. See if there is anything relevant in the logs (especially any errors)

**Comment by theCalcaholic** [comment]
Closed due to inactivity
