### ISSUE TITLE
Failed to enable Secret for Nextcloud 27.0.1

### ISSUE THREAD

**Issue by kevinkuan1969** [theCalcaholic/nextcloud-secrets#39]
Successful to enable all the applications except Secret. Here the screenshot mentioned the error in SQL table.  

![image](https://github.com/theCalcaholic/nextcloud-secrets/assets/80019930/82f033f7-9a7b-499c-b7c7-19ceeab5f193)

**Comment by theCalcaholic** [comment]
Thanks for reporting.
Please answer the followin questions:
Did you successfully use an earlier version of secrets?
Which database are you using? 

There seems to be a secret with invalid data in your database. Your issue should be fixable by deleting the faulty secret.
Assuming the table prefix for your instance is `oc`, you should be able to find out which secret(s) is causing it by running an SQL statement like this:
```sql
SELECT * FROM oc_secrets WHERE expires = '0000-00-00 00:00:00';
```
and delete them with:
```sql
DELETE FROM oc_secrets WHERE expires = '0000-00-00 00:00:00';
```

**Comment by theCalcaholic** [comment]
Closed due to inactivity
