### ISSUE TITLE
Reduce loglevel from `warning` to `info`

### ISSUE THREAD

**Issue by ernolf** [theCalcaholic/nextcloud-secrets#40]
The app throws informations as `warning`,

here:

https://github.com/theCalcaholic/nextcloud-secrets/blob/a2d7a8275ae8c5bad6eb9b3023387c7a95e5aca8/lib/Cron/SecretCleanup.php#L31

and here:

https://github.com/theCalcaholic/nextcloud-secrets/blob/a2d7a8275ae8c5bad6eb9b3023387c7a95e5aca8/lib/Db/SecretMapper.php#L99

Speaks something against classifying these messages as `info`, since it concerns normal operations of the app and no errors.

ernolf

**Comment by theCalcaholic** [comment]
You are right, it would make more sense to use a lower log level 👍

**Comment by theCalcaholic** [comment]
Fixed in 1.5.2
