### ISSUE TITLE
Support for Nextcloud 28 

### ISSUE THREAD

**Issue by eddiermar** [theCalcaholic/nextcloud-secrets#43]
Please support NC 28!

**Comment by flyize** [comment]
I can confirm that it does not work with NC 28. Everything seems to work until you attempt to share the URL. The given URL will not work.

**Comment by theCalcaholic** [comment]
Thank you for the issue and thank you @flyize for the additional information. I'm still testing this, the next release will add support for NC 28.
Sorry for the delay, I got caught up in other pressing matters

**Comment by theCalcaholic** [comment]
Nextcloud 28 support has been added in the latest release
