### ISSUE TITLE
Version 2.0.2: Doesn't show secret after password: "CSRF check failed"

### ISSUE THREAD

**Issue by stoamanderl** [theCalcaholic/nextcloud-secrets#50]
![Bildschirmfoto 2024-07-14 um 21 23 20](https://github.com/user-attachments/assets/4e724d0a-c661-4a3c-8cd8-53e02314e1e4)

I can "protect" the secret by a password now. But after password-input the receiver cannot se the secret. Instead he get's an error message saying "CSRF check faild".

**Comment by theCalcaholic** [comment]
Hm, I cannot reproduce this issue. Can you try retrieving a secret from a private tab to see if this behavior is somehow related to your session?

**Comment by theCalcaholic** [comment]
Closed due to inactivity.
