### ISSUE TITLE
Delete secret logs "Undefined property: OCA\Secrets\Db\Secret::$getTitle"

### ISSUE THREAD

**Issue by ViktorF** [theCalcaholic/nextcloud-secrets#51]
When clicking "Delete secret" on any secret I get the following Error in the Nextcloud Log. The Secret still deletes successful.

![image](https://github.com/user-attachments/assets/06238e63-ae2f-477e-b93e-39c09c3a6a4a)

{"reqId":"IcqpujypQ40otSIjQlVo","level":3,"time":"2024-08-12T15:52:34+02:00","remoteAddr":"***","user":"***","app":"PHP","method":"DELETE","url":"/ocs/v2.php/apps/secrets/api/v1/secrets/66f2ba1c72c64d2481b7bf9d09769083","message":"Undefined property: OCA\\Secrets\\Db\\Secret::$getTitle at /var/www/nextcloud/apps/secrets/lib/Controller/SecretApiController.php#209","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36","version":"29.0.4.1","data":{"app":"PHP"},"id":"66ba13a815e4b"}

[PHP] Error: Undefined property: OCA\Secrets\Db\Secret::$getTitle at /var/www/nextcloud/apps/secrets/lib/Controller/SecretApiController.php#209
	DELETE /ocs/v2.php/apps/secrets/api/v1/secrets/66f2ba1c72c64d2481b7bf9d09769083

![image](https://github.com/user-attachments/assets/a40c7bb6-3970-43b3-a44f-ed7199844415)

My App Version is 2.0.3 but I also had it on 2.0.2

**Comment by theCalcaholic** [comment]
Will be fixed in the next release (2.1.1) thanks to @vitormattos  :)
