### ISSUE TITLE
No new secret can be created

### ISSUE THREAD

**Issue by hhlotter** [theCalcaholic/nextcloud-secrets#53]
Using Nextcloud 29.0.5
Installed the App from the App Store
App shows up at the users
However, when pressing the button "Neues Geheimnis" nothing happens ...

**Comment by hhlotter** [comment]
Just checked: when logged in as Admin, it works perfectly. Really nice ;-)

However as a normal user the described issue persists.

**Comment by theCalcaholic** [comment]
Hi, thanks for the report. Can you press F12 after a failed attempt to create a secret and see if there are any errors?

**Comment by hhlotter** [comment]
yes. And I believe I now know the problem.

As Admin I was logged in locally and not via the DDNS Service. So I tried to log in as user locally and it works perfectly.

I believe the issue is that I still have to set up the DDNS Service via https and not only http ...

So problem on my side.

**Comment by hhlotter** [comment]
Thanks

**Comment by theCalcaholic** [comment]
Ah yes, that would explain it. The cryptography of Nextcloud secrets requires https to work (see #4 ).
