### ISSUE TITLE
Language inconsistency: English text appears in Hungarian interface

### ISSUE THREAD

**Issue by leventeludnik** [theCalcaholic/nextcloud-secrets#55]
When using the Nextcloud Secrets plugin with the Hungarian language interface, some parts of the text are still displayed in English. This creates a mixed-language experience, which might confuse users expecting a fully translated interface.

Example of English Hungarian mixed text:
"A következő titok biztonságosan lett megosztva Önnel:"
"Revealing will delete the secret from the server. You will not be able to retrieve it again."
"I understand. Reveal and destroy Secret."

Steps to reproduce:
Set the Nextcloud interface language to Hungarian.
Use the Nextcloud Secrets plugin to share a secret.
Notice that some of the messages are still in English.
Expected behavior:
All text, especially user-facing messages, should be fully translated into Hungarian when the interface language is set to Hungarian.

Additional context:
Nextcloud version: Nextcloud Hub 8 29.0.7
Nextcloud Secrets plugin version: 2.0.3
Please let me know if additional information is needed, and thank you for your work on this plugin!

**Comment by theCalcaholic** [comment]
Hi, thank you for reporting.
That usually means that the localization is incomplete.
There's no real way for me to fix it, because the localization is created by volunteers from the Nextcloud community.
Maybe, however, the translations are ready by now and all it takes is a new release of the app. I'll soon release again and this could fix the issue

**Comment by leventeludnik** [comment]
Some line is missing from Hungarian version:

"Revealing will delete the secret from the server. You will not be able to retrieve it again." : "A titok felfedése törölni fogja azt a szerverről. Ezt követően nem tudja visszaállítani.",
"I understand. Reveal and destroy Secret." : "Értem. Titok felfedése és megsemmisítése.",
"This path has changed. Redirecting you to the new location. If this doesn't work, click the following link:" : "Ez az útvonal megváltozott. Átirányítjuk az új helyre. Ha ez nem működik, kattintson az alábbi hivatkozásra:",
"Go to secret" : "Menj a titokhoz"

**Comment by theCalcaholic** [comment]
Thank you, I added them to the translation files (will be part of the next release). :)
