### ISSUE TITLE
encrypted file attachments

### ISSUE THREAD

**Issue by neidert** [theCalcaholic/nextcloud-secrets#8]
It would be great to be able to add encrypted file attachments to the Secret.

**Comment by theCalcaholic** [comment]
I was thinking about this, but I considered implementing it as a different share "type" (download instead of copy).

Would that fit your use case?

**Comment by vitormattos** [comment]
Already is possible share a file with password. Maybe, will be good to have the possibility to share the generated password by `secrets`, but this didn't make the process more secure because in a time will be necessary send the password from shared link or `secret`.

**Comment by theCalcaholic** [comment]
Yeah, the use case I have in mind is sharing credentials, e.g. a key file or service account in json format.
The benefit from secrets is in my opinion a) the e2e encryption and b) that you can be sure that it wasn't retrieved by anyone else if the correct receiver got the file.

Generic file sharing is not the use case I have in mind

**Comment by theCalcaholic** [comment]
I've given this some more thought - maybe it's sufficient for this use case to add a download button :)

**Comment by sergeng** [comment]
bump

**Comment by theCalcaholic** [comment]
@sergeng 

Please don't post messages that don't add anything to the discussion (especially not on feature requests). If you want to express your interest in a feature, use emoji reactions on the original issue instead.

**Comment by theCalcaholic** [comment]
With the latest release (v1.5.1) there is now a download button in the share page. I'll close this issue for now as I have no plans at the moment to implement actual e2e encrypted file sharing
